version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
  - package-ecosystem: gomod
    directory: .sage
    schedule:
      interval: weekly
    cooldown:
      default-days: 7
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
